### ISSUE TITLE
The scripts can not work on Python3?

### ISSUE THREAD

**Issue by ZXR-v2** [kotfic/i2b2_evaluation_scripts#3]
There are so many mistakes when the scripts run on Python3.

**Comment by kotfic** [comment]
@Zhengxuru This project was completed in 2014 when wide spread support for Python 3 in upstream packages was simply not available. There is no plan/staffing to update this to Python 3.  PR's are welcome!

**Comment by ZXR-v2** [comment]
Thanks for your work! Can these scripts run on Python2.7 or other Python 2 versions?
